### PR TITLE
Community Design #31

### PR DESCRIPTION
**Pull request by Mte90**
Working on https://github.com/mozilla/Community-Design/issues/31

I have some problem with the compiling of the css that i get error on npm run serve and npm run build and the css is not updated.

### CODE REVIEW

**Comment by bwinton** [comment]
Hmm…  Can you paste the error you're seeing?

**Comment by Mte90** [comment]
With `npm run serve` I get on the browser:
`Error: Cannot find module "./styles/base.scss"`
With `npm run build` on the console i get that:
[removed for cleaning]

I see that are many packages not updated on package.json

**Comment by bwinton** [comment]
Hmm.  I'm using node v.5.5.0 and npm v3.5.3.  Would it be possible for you to upgrade?  (Or if not, try running `npm rebuild node-sass` and see if that helps…)

**Comment by bwinton** [comment]
(If neither of those work, you could also delete your node_modules directory, and try to re-install everything, to grab the node v.4.3.0 versions of packages, but please don't include any changes from those in your commit.  :wink:)

**Comment by Mte90** [comment]
I have nodejs 4.3.0 and npm 2.14.2, with `npm rebuild node-sass` the problem persist.
I can try to update.

**Comment by Mte90** [comment]
I have updated nodejs to 5.6.0 and npm to 3.7.1 but the problem persist:
[removed for cleaning]

**Comment by Mte90** [comment]
Ok with `npm rebuild node-sass` now is working the compiling :-)

**Comment by bwinton** [comment]
Phew!  :smile:
I'm probably going to review this tomorrow morning (GMT-5), so if there are any other changes you want to make before then go for it, otherwise I'll let you know if there's anything else that needs cleaning up.

And thank you for persisting in getting the build working!

**Comment by Mte90** [comment]
screenshot-5
Now is that like but I am not sure to have uploaded the css compiled.

**Comment by bwinton** [comment]
That looks pretty good!  What do you think about picking some icons from [this set](http://firefoxux.github.io/firefox-svg-icons/viewer/), and putting them to the left of the text?  (We can replace them with custom-crafted versions later, if it looks good…)

And don't worry too much about the compiled CSS.  I can always fix that later.  :smiley:

**Comment by Mte90** [comment]
I work on that asap.

**Comment by Mte90** [comment]
Uhm I can see that the className parameter is ignored on componenets/TableOfContents.jsx:

```
return ([].concat(<ListItem
          i={i}
          item={item}
                        />).concat(
```

I not know React so i not know how to fix that.

**Comment by bwinton** [comment]
Okay, I've put it up [over here](http://people.mozilla.org/~bwinton/StyleGuide/#/components/inputs), and taken a look at it, and here are the small things I noticed that it would be nice to fix:
1) The coloured bar should be all the way to the left, not indented, and should be 4px wide instead of 3px wide.
2) The font-size should be 11px instead of 18px.
3) The background of each section should be lighter when you hover over it.
4) The sections shouldn't have any padding between them. (So if you hover over the item below the selected item, there shouldn't be any space between the two, like in this image:
screenshot 2016-02-12 11 40 47

@shorlander is also going to leave some comments in an hour or so…

Having said that, we're both very happy with how it looks, and agree that it's a huge improvement!  :+1:

**Comment by bwinton** [comment]
Oh, yeah, that className is for the loaded page, although I don't see any reason why it can't be put on the ListItem, too…  Give me a minute and I'll make a pull request against your repo.  :grinning:

**Comment by Mte90** [comment]
screenshot
Last update, with 11px the font is very very small I changed to 16px.

**Comment by bwinton** [comment]
Can we get the .subitem text indented, but leave the colour bar on the left?

**Comment by Mte90** [comment]
screenshot1
In this case addons is a subitem, I removed the identation.

**Comment by Mte90** [comment]
screenshot2
The actual version, I think that there aren't all the icons for every menu items.
The svg is the same but with css I invert the color to get white color.

At the end i merge all the commits in unique.

**Comment by Mte90** [comment]
screenshot3
Finished!

**Comment by Mte90** [comment]
[selfie-0](https://github.com/thieman/github-selfies/)
Merged in one commit!

**Comment by bwinton** [comment]
So, I think we've waited long enough for @shorlander's reply, so I'm just going to merge it, and we can fix anything he mentions in followup issues.  :grinning:

Thank you so much for your hard work, @Mte90!

**Pull request merged**
